/**
 * Location lookups: county list, tax/insurance estimates, calculator defaults.
 * Data generated by scripts/sync-loan-limits.mjs from official HUD CHUMS files.
 */
import countiesJson from "../../public/data/counties.json";
import estimatesJson from "../../public/data/county-estimates.json";
import {
  STATES,
  getState,
  inputsFromState,
  type StateData,
} from "./states";
import { DEFAULT_INPUTS } from "./defaults";

export type CountyRecord = {
  fips: string;
  name: string;
  stateAbbr: string;
  stateSlug: string;
  slug: string;
};

export type LocationSelection = {
  stateSlug: string;
  countyFips: string;
};

const COUNTIES = countiesJson as CountyRecord[];
const ESTIMATES = (
  estimatesJson as {
    estimates: Record<
      string,
      { tax: number; insurance: number; median: number }
    >;
  }
).estimates;

const countiesByStateSlug = new Map<string, CountyRecord[]>();
for (const c of COUNTIES) {
  if (!c.stateSlug) continue;
  const list = countiesByStateSlug.get(c.stateSlug);
  if (list) list.push(c);
  else countiesByStateSlug.set(c.stateSlug, [c]);
}
for (const list of countiesByStateSlug.values()) {
  list.sort((a, b) => a.name.localeCompare(b.name));
}

const countyByFips = new Map(COUNTIES.map((c) => [c.fips, c]));

export function getCountiesForState(stateSlug: string): CountyRecord[] {
  return countiesByStateSlug.get(stateSlug) ?? [];
}

export function getCounty(fips: string): CountyRecord | undefined {
  return countyByFips.get(fips);
}

export function findCountyInState(
  stateSlug: string,
  countyFipsOrSlug: string,
): CountyRecord | undefined {
  const list = getCountiesForState(stateSlug);
  return (
    list.find((c) => c.fips === countyFipsOrSlug) ||
    list.find((c) => c.slug === countyFipsOrSlug)
  );
}

export type LocationInputs = {
  homePrice: number;
  downPayment: number;
  propertyTaxRate: number;
  annualHomeInsurance: number;
};

/** Defaults for national / state / county selection. */
export function inputsFromLocation(
  stateSlug?: string | null,
  countyFips?: string | null,
): Partial<LocationInputs> {
  if (!stateSlug) {
    return {
      homePrice: DEFAULT_INPUTS.homePrice,
      downPayment: DEFAULT_INPUTS.downPayment,
      propertyTaxRate: DEFAULT_INPUTS.propertyTaxRate,
      annualHomeInsurance: DEFAULT_INPUTS.annualHomeInsurance,
    };
  }

  const state = getState(stateSlug);
  if (!state) {
    return {
      homePrice: DEFAULT_INPUTS.homePrice,
      downPayment: DEFAULT_INPUTS.downPayment,
      propertyTaxRate: DEFAULT_INPUTS.propertyTaxRate,
      annualHomeInsurance: DEFAULT_INPUTS.annualHomeInsurance,
    };
  }

  const base = inputsFromState(state);
  if (!countyFips) return base;

  const estimate = ESTIMATES[countyFips];
  if (!estimate) return base;

  const homePrice = estimate.median > 0 ? estimate.median : base.homePrice;
  return {
    homePrice,
    downPayment: Math.round(homePrice * 0.2),
    propertyTaxRate: estimate.tax,
    annualHomeInsurance: estimate.insurance,
  };
}

export function resolveState(stateSlug?: string | null): StateData | undefined {
  return stateSlug ? getState(stateSlug) : undefined;
}

export { STATES, COUNTIES };
